#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Frontend checks
npm run test --prefix client -- --run || exit 1
npm run lint --prefix client || exit 1
npm audit --prefix client || exit 1

# Backend checks
cd api || exit 1
if [ ! -d "venv" ]; then
  if [ "$(uname -s | grep -i 'mingw\|cygwin\|msys')" ]; then
    setup.bat || exit 1
  else
    sh setup.sh || exit 1
  fi
fi
if [ -d "venv" ]; then
  if [ "$(uname -s | grep -i 'mingw\|cygwin\|msys')" ]; then
    venv\Scripts\activate.bat || venv\Scripts\Activate.ps1 || true
  else
    . venv/Scripts/activate || true
  fi
fi
python -m pip install -r requirements.txt
python test_app.py || exit 1
ruff check . || exit 1
pip-audit || exit 1
cd .. 